// Code generated by irpc v0.0.2 (h1:ebZ5bSKiXdz/G0ifYvQ...); DO NOT EDIT
// Source: irpc-demo/services/rtcmsg/service.go
package rtcmsg

import (
	"context"
	"fmt"
	"github.com/marben/irpc/irpcgen"
)

var _SessionIrpcId = irpcgen.ServiceId(0x999d8e9f39323d64)

// SessionIrpcService provides [Session] interface over irpc
type SessionIrpcService struct {
	impl Session
}

// NewSessionIrpcService returns new [irpcgen.Service] forwarding [Session] network calls to impl
func NewSessionIrpcService(impl Session) *SessionIrpcService {
	return &SessionIrpcService{
		impl: impl,
	}
}

// Id implements [irpcgen.Service] interface.
func (s *SessionIrpcService) Id() irpcgen.ServiceId {
	return _SessionIrpcId
}

// GetFuncCall implements [irpcgen.Service] interface
func (s *SessionIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // Send
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			var args _irpc_Session_SendReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				var resp _irpc_Session_SendResp
				resp.p0 = s.impl.Send(args.msg)
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// SessionIrpcClient implements [Session] interface. It by forwards calls over network to [SessionIrpcService] that provides the implementation.
type SessionIrpcClient struct {
	endpoint irpcgen.Endpoint
}

func NewSessionIrpcClient(endpoint irpcgen.Endpoint) (*SessionIrpcClient, error) {
	if err := endpoint.RegisterClient(_SessionIrpcId); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &SessionIrpcClient{endpoint: endpoint}, nil
}

// Send implements [Session]
//
func (_c *SessionIrpcClient) Send(msg Message) error {
	var req = _irpc_Session_SendReq{
		msg: msg,
	}
	var resp _irpc_Session_SendResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _SessionIrpcId, 0, req, &resp); err != nil {
		return err
	}
	return resp.p0
}

type _irpc_Session_SendReq struct {
	msg Message
}

func (s _irpc_Session_SendReq) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, s Message) error {
		if err := irpcgen.EncString(enc, s.Name); err != nil {
			return fmt.Errorf("serialize s.Name of type string: %w", err)
		}
		if err := irpcgen.EncString(enc, s.Text); err != nil {
			return fmt.Errorf("serialize s.Text of type string: %w", err)
		}
		return nil
	}(e, s.msg); err != nil {
		return fmt.Errorf("serialize \"msg\" of type Message: %w", err)
	}
	return nil
}
func (s *_irpc_Session_SendReq) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, s *Message) error {
		if err := irpcgen.DecString(dec, &s.Name); err != nil {
			return fmt.Errorf("deserialize s.Name of type string: %w", err)
		}
		if err := irpcgen.DecString(dec, &s.Text); err != nil {
			return fmt.Errorf("deserialize s.Text of type string: %w", err)
		}
		return nil
	}(d, &s.msg); err != nil {
		return fmt.Errorf("deserialize msg of type Message: %w", err)
	}
	return nil
}

type _irpc_Session_SendResp struct {
	p0 error
}

func (s _irpc_Session_SendResp) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, v error) error {
		isNil := v == nil
		if err := irpcgen.EncIsNil(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_Error_0_ := v.Error()
		if err := irpcgen.EncString(enc, _Error_0_); err != nil {
			return fmt.Errorf("serialize \"v.Error()\" of type string: %w", err)
		}
		return nil
	}(e, s.p0); err != nil {
		return fmt.Errorf("serialize type error: %w", err)
	}
	return nil
}
func (s *_irpc_Session_SendResp) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, s *error) error {
		var isNil bool
		if err := irpcgen.DecIsNil(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w", err)
		}
		if isNil {
			return nil
		}
		var impl _error_Session_impl
		if err := irpcgen.DecString(dec, &impl._Error_0_); err != nil {
			return fmt.Errorf("deserialize \"_Error_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type error: %w", err)
	}
	return nil
}

type _error_Session_impl struct {
	_Error_0_ string
}

func (i _error_Session_impl) Error() string {
	return i._Error_0_
}
